const http=require('http'),fs=require('fs'),path=require('path'),{WebSocketServer}=require('ws');
const PORT=process.env.PORT||3000;const rooms=new Map();
const server=http.createServer((req,res)=>{const p=req.url==='/'?'/index.html':req.url;const f=path.join(__dirname,p);if(!f.startsWith(__dirname)||!fs.existsSync(f)){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':f.endsWith('.html')?'text/html; charset=utf-8':'text/plain; charset=utf-8'});res.end(fs.readFileSync(f));});
const wss=new WebSocketServer({server});
const cards=[
['炎剣フレア','weapon',4,18,'fire','攻撃時に10%で燃焼'],['雷槍ボルト','weapon',5,21,'thunder','攻撃時に感電'],['氷刃フロスト','weapon',4,16,'ice','攻撃時に凍結'],['聖弓ルミナ','weapon',6,24,'light','攻撃時に再生を付与'],['黒鎌ナイトメア','weapon',7,28,'dark','攻撃時に吸血'],['毒爪ヴェノム','weapon',3,13,'poison','攻撃時に毒'],
['鉄壁シールド','armor',3,10,'','被ダメージを10%軽減'],['炎竜の盾','armor',5,14,'fire','被ダメージを15%軽減'],['氷晶の鎧','armor',4,12,'ice','被ダメージを12%軽減'],['闇衣カース','armor',5,9,'dark','状態異常を1ターン短縮'],
['火球','spell',3,20,'fire','燃焼を2ターン付与'],['雷撃','spell',4,24,'thunder','感電を2ターン付与'],['氷結','spell',3,14,'ice','凍結を1ターン付与'],['聖光','spell',5,28,'light','再生を2ターン付与'],['暗黒弾','spell',5,30,'dark','与えたダメージの35%回復'],['毒霧','spell',3,10,'poison','毒を3ターン付与'],
['大回復','heal',4,28,'','HPを28回復'],['応急手当','heal',2,14,'','HPを14回復'],['魔力転換','heal',0,0,'','MPを10回復'],['吸血','spell',4,16,'dark','与えたダメージの50%回復'],
['カウンター','special',3,0,'','次に受ける攻撃の40%を反射'],['強奪','special',2,0,'','相手の手札を1枚奪う'],['破壊','special',5,0,'','相手の武器を破壊'],['二連撃','special',5,0,'','武器攻撃を2回行う'],['神の加護','special',4,0,'','HP+18、MP+6、防御力UP'],['浄化','special',2,0,'','自分の状態異常を全解除']
];
function deck(){let d=[];for(let i=0;i<3;i++)for(const c of cards)d.push(c);return d.sort(()=>Math.random()-.5)}
function player(){return{hp:100,maxHp:100,mp:12,maxMp:20,hand:[],weapon:null,armor:null,shield:0,guard:false,counter:false,statuses:[],ws:null,deck:[]}}
const statusInfo={poison:{name:'毒',icon:'☠️',desc:'ターン開始時に5ダメージ',cls:'bad'},burn:{name:'燃焼',icon:'🔥',desc:'ターン開始時に7ダメージ',cls:'bad'},freeze:{name:'凍結',icon:'❄️',desc:'次のターン行動不能',cls:'bad'},shock:{name:'感電',icon:'⚡',desc:'受けるダメージ+20%',cls:'bad'},regen:{name:'再生',icon:'💚',desc:'ターン開始時に8回復',cls:'good'},atkUp:{name:'攻撃力UP',icon:'⚔️',desc:'攻撃ダメージ+25%',cls:'good'},defUp:{name:'防御力UP',icon:'🛡️',desc:'受けるダメージ-25%',cls:'good'}};
function send(ws,x){if(ws&&ws.readyState===1)ws.send(JSON.stringify(x))}function broadcast(r,x){r.players.forEach(p=>send(p.ws,x))}
function statusView(p){return p.statuses.map(s=>({id:s.id,turns:s.turns,info:statusInfo[s.id]}))}
function state(r){return r.players.map(p=>({hp:p.hp,maxHp:p.maxHp,mp:p.mp,maxMp:p.maxMp,hand:p.hand.map((c,j)=>({i:j,name:c[0],type:c[1],cost:c[2],power:c[3],attr:c[4],desc:c[5]})),weapon:p.weapon?{name:p.weapon[0],power:p.weapon[3],cost:p.weapon[2],attr:p.weapon[4],desc:p.weapon[5]}:null,armor:p.armor?{name:p.armor[0],power:p.armor[3],cost:p.armor[2],attr:p.armor[4],desc:p.armor[5]}:null,shield:p.shield,guard:p.guard,counter:p.counter,statuses:statusView(p)}))}
function pub(r,msg=''){broadcast(r,{type:'state',turn:r.turn,state:state(r),log:r.log.slice(-10),msg})}
function draw(p,n=1){while(n--&&p.deck.length)p.hand.push(p.deck.pop())}
function addStatus(p,id,turns){const old=p.statuses.find(s=>s.id===id);if(old)old.turns=Math.max(old.turns,turns);else p.statuses.push({id,turns})}
function has(p,id){return p.statuses.some(s=>s.id===id)}
function removeStatus(p,id){p.statuses=p.statuses.filter(s=>s.id!==id)}
function setup(r){r.players.forEach(p=>{const w=p.ws;Object.assign(p,player());p.ws=w;p.deck=deck();draw(p,6)});r.turn=0;r.log=['対戦開始！先攻プレイヤーのターン'];startTurn(r)}
function startTurn(r){const p=r.players[r.turn];let skip=false;for(const s of [...p.statuses]){if(s.id==='poison'){p.hp=Math.max(0,p.hp-5);r.log.push(`P${r.turn+1}は毒で5ダメージ`)}if(s.id==='burn'){p.hp=Math.max(0,p.hp-7);r.log.push(`P${r.turn+1}は燃焼で7ダメージ`)}if(s.id==='regen'){p.hp=Math.min(p.maxHp,p.hp+8);r.log.push(`P${r.turn+1}は再生で8回復`)}s.turns--;if(s.id==='freeze'&&s.turns>=0){skip=true;s.turns=0;r.log.push(`P${r.turn+1}は凍結している！`)}}p.statuses=p.statuses.filter(s=>s.turns>0);if(p.hp<=0)return finish(r,1-r.turn);if(skip){r.log.push(`P${r.turn+1}は行動できない`);p.mp=Math.min(p.maxMp,p.mp+3);draw(p,1);r.turn=1-r.turn;return startTurn(r)}pub(r)}
function setupLog(r){r.log=[]}
function dmg(r,a,b,n,kind){let reduced=0;if(b.guard){reduced+=Math.floor(n*.5);b.guard=false}if(b.armor&&kind==='attack')reduced+=Math.floor(n*(b.armor[3]/100));if(has(b,'defUp'))reduced+=Math.floor(n*.25);if(has(b,'shock'))n=Math.ceil(n*1.2);n=Math.max(0,n-reduced);b.hp=Math.max(0,b.hp-n);r.log.push(`${kind==='spell'?'魔法':'攻撃'}で ${n} ダメージ${reduced?`（${reduced}軽減）`:''}`);if(b.counter){b.counter=false;const c=Math.floor(n*.4);a.hp=Math.max(0,a.hp-c);r.log.push(`⚡カウンターで${c}ダメージ反射！`)}}
function weaponHit(r,a,b,base){let n=base+Math.floor(Math.random()*5)-2;dmg(r,a,b,n,'attack');if(a.weapon){const x=a.weapon[4];if(x==='poison')addStatus(b,'poison',3);if(x==='fire'&&Math.random()<.5)addStatus(b,'burn',2);if(x==='ice')addStatus(b,'freeze',1);if(x==='thunder')addStatus(b,'shock',2);if(x==='light')addStatus(a,'regen',2);if(x==='dark')a.hp=Math.min(a.maxHp,a.hp+Math.floor(n*.25))}}
function act(r,idx,data){if(idx!==r.turn||r.turn<0)return;const a=r.players[idx],b=r.players[1-idx];if(a.hp<=0)return;if(data.type==='guard'){a.guard=true;r.log.push(`P${idx+1}は防御態勢！被ダメージ50%軽減`);return end(r)}if(data.type==='draw'){draw(a,2);r.log.push(`P${idx+1}はカードを2枚引いた`);return end(r)}const c=a.hand[data.card];if(!c)return;const cost=c[2];if(a.mp<cost){send(a.ws,{type:'error',msg:'MPが足りません'});return}a.mp-=cost;a.hand.splice(data.card,1);switch(c[1]){case'weapon':a.weapon=c;r.log.push(`P${idx+1}は【${c[0]}】を装備`);break;case'armor':a.armor=c;r.log.push(`P${idx+1}は【${c[0]}】を装備`);break;case'spell':{let n=c[3]+Math.floor(Math.random()*7)-3;dmg(r,a,b,n,'spell');if(c[4]==='ice')addStatus(b,'freeze',1);if(c[4]==='poison')addStatus(b,'poison',3);if(c[4]==='fire')addStatus(b,'burn',2);if(c[4]==='thunder')addStatus(b,'shock',2);if(c[4]==='light')addStatus(a,'regen',2);if(c[4]==='dark')a.hp=Math.min(a.maxHp,a.hp+Math.floor(n*.35));break}case'heal':if(c[0]==='魔力転換'){a.mp=Math.min(a.maxMp,a.mp+10);r.log.push('MPを10回復')}else{a.hp=Math.min(a.maxHp,a.hp+c[3]);r.log.push(`HPを${c[3]}回復`)}break;case'special':if(c[0]==='カウンター'){a.counter=true;r.log.push('カウンターを構えた！')}else if(c[0]==='強奪'){if(b.hand.length){const k=Math.floor(Math.random()*b.hand.length);a.hand.push(b.hand.splice(k,1)[0]);r.log.push('相手の手札を1枚奪った')}}else if(c[0]==='破壊'){b.weapon=null;r.log.push('相手の武器を破壊！')}else if(c[0]==='二連撃'){const n=a.weapon?a.weapon[3]:10;weaponHit(r,a,b,n);if(b.hp>0)weaponHit(r,a,b,n);r.log.push('二連撃！')}else if(c[0]==='神の加護'){a.hp=Math.min(a.maxHp,a.hp+18);a.mp=Math.min(a.maxMp,a.mp+6);a.guard=true;addStatus(a,'defUp',2);r.log.push('神の加護！HP+18 MP+6 防御力UP')}else if(c[0]==='浄化'){a.statuses=[];r.log.push('状態異常をすべて解除！')}break}if(a.weapon&&Math.random()<.12&&c[1]!=='weapon'){r.log.push(`【${a.weapon[0]}】の追加攻撃！`);weaponHit(r,a,b,5)}end(r)}
function attack(r,idx){if(idx!==r.turn||r.turn<0)return;const a=r.players[idx],b=r.players[1-idx];if(a.mp<1)return;if(!a.weapon){send(a.ws,{type:'error',msg:'まず武器を装備してください'});return}a.mp--;weaponHit(r,a,b,a.weapon[3]);end(r)}
function finish(r,w){r.log.push(`🏆 P${w+1}の勝利！`);r.turn=-1;pub(r,'対戦終了')}
function end(r){if(r.players[1].hp<=0||r.players[0].hp<=0)return finish(r,r.players[0].hp>0?0:1);const p=r.players[r.turn];p.mp=Math.min(p.maxMp,p.mp+3);draw(p,1);r.turn=1-r.turn;r.log.push(`P${r.turn+1}のターン！`);startTurn(r)}
wss.on('connection',ws=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.action==='join'){const code=(m.room||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(!code)return;let r=rooms.get(code);if(!r){r={players:[],turn:0,log:[],code};rooms.set(code,r)}if(r.players.length>=2)return send(ws,{type:'error',msg:'この部屋は満員です'});const p=player();p.ws=ws;r.players.push(p);send(ws,{type:'joined',index:r.players.length-1,code});if(r.players.length===2)setup(r);else send(ws,{type:'waiting',msg:'相手の参加を待っています…'});return}const r=[...rooms.values()].find(x=>x.players.some(p=>p.ws===ws));if(!r)return;const idx=r.players.findIndex(p=>p.ws===ws);if(m.action==='play')act(r,idx,m);else if(m.action==='attack')attack(r,idx);else if(m.action==='guard')act(r,idx,{type:'guard'});else if(m.action==='draw')act(r,idx,{type:'draw'})});ws.on('close',()=>{for(const[k,r]of rooms){const i=r.players.findIndex(p=>p.ws===ws);if(i>=0){r.players.splice(i,1);broadcast(r,{type:'error',msg:'相手が退出しました'});if(!r.players.length)rooms.delete(k);break}}})});
server.listen(PORT,'0.0.0.0',()=>console.log(`ready on ${PORT}`));
